#!/usr/bin/env python3
"""Assemble results/report.md from the run tables and claim measurements."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from paths import RESULTS_DIR, ensure_directories  # noqa: E402


def md_table(df: pd.DataFrame, floatfmt: str = "{:.3f}") -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(str(c) for c in cols) + " |",
           "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            if isinstance(v, float):
                cells.append("" if pd.isna(v) else floatfmt.format(v))
            else:
                cells.append(str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def main() -> None:
    ensure_directories()
    runs = pd.read_csv(RESULTS_DIR / "runs.csv")
    claims = json.loads((RESULTS_DIR / "claims.json").read_text())
    ab = pd.read_csv(RESULTS_DIR / "ablation_significance.csv")
    meta = json.loads((RESULTS_DIR / "panel_meta.json").read_text())
    t1 = pd.read_csv(RESULTS_DIR / "claim_c1_single_market.csv")
    t2 = pd.read_csv(RESULTS_DIR / "claim_c2_breadth.csv")
    t4 = pd.read_csv(RESULTS_DIR / "claim_c4_clusters.csv")
    t5 = pd.read_csv(RESULTS_DIR / "claim_c5_horizons.csv")
    base = runs[runs["label"] == "baseline"].iloc[0]

    parts: list[str] = []
    add = parts.append

    add("# Measurements\n")
    add("Generated by `make report`. The frozen rule set is README.md "
        "section 3; nothing here was used to choose a parameter.\n")

    add("## Panel\n")
    add(md_table(pd.DataFrame([meta])))
    add(f"\nFunding covers {claims['funding_coverage_of_tradeable_symbol_days']:.1%} "
        "of tradeable symbol-days; uncovered exposure is charged zero.\n")

    add("## Baseline\n")
    keep = ["total_return", "cagr", "ann_vol", "sharpe_net", "sharpe_gross",
            "max_drawdown", "design_sharpe_net", "holdout_sharpe_net",
            "ann_turnover", "avg_gross_exposure", "cost_drag_ann",
            "funding_drag_ann", "avg_positions", "avg_held_ex_ante_vol",
            "avg_target_tracking_error"]
    add(md_table(pd.DataFrame({"statistic": keep,
                               "value": [base[k] for k in keep]})))

    add("\n## All runs\n")
    cols = ["group", "label", "total_return", "cagr", "ann_vol", "sharpe_net",
            "sharpe_gross", "max_drawdown", "design_sharpe_net",
            "holdout_sharpe_net", "ann_turnover", "cost_drag_ann",
            "funding_drag_ann", "avg_held_ex_ante_vol",
            "avg_target_tracking_error"]
    add(md_table(runs[cols]))

    add("\n## Variant significance\n")
    add("`sharpe_diff_ci_*` is a 95% stationary-bootstrap interval (mean "
        "block 21 days, 2000 resamples) for Sharpe(variant) - Sharpe(baseline), "
        "resampling both series on the same block indices.\n")
    add(md_table(ab[["group", "label", "sharpe_net", "sharpe_vs_baseline",
                     "sharpe_diff_ci_lo", "sharpe_diff_ci_hi"]]))

    add("\n## C1 single-market Sharpe\n")
    add(md_table(pd.DataFrame([{
        "markets": claims["C1"]["markets"],
        "median_net": claims["C1"]["median_sharpe_net"],
        "mean_net": claims["C1"]["mean_sharpe_net"],
        "median_gross": claims["C1"]["median_sharpe_gross"],
        "mean_gross": claims["C1"]["mean_sharpe_gross"],
        "share_positive_net": claims["C1"]["share_positive_net"],
        "claimed": claims["C1"]["claimed"],
    }])))
    add("\nBest and worst five markets:\n")
    add(md_table(pd.concat([t1.head(5), t1.tail(5)])))

    add("\n## C2/C3 breadth scaling\n")
    add(md_table(t2))
    c = claims["C2_C3"]
    add(f"\nGross-return point-in-time random-priority portfolios expanding from "
        f"{c['c3_expansion']['from_n']} to {c['c3_expansion']['to_n']} "
        f"market slots multiply Sharpe by "
        f"{c['c3_expansion']['observed_multiple']:.2f}. This is a nominal-count "
        "venue diagnostic; the source's square-root rule is stated for "
        "independent breadth.\n")

    add("\n## C4 diversification and effective breadth\n")
    add(md_table(t4))
    c4 = claims["C4"]
    add(f"\nEffective breadth of {c4['nominal_breadth']} single-market return "
        f"streams: {c4['effective_breadth_of_strategy_returns']:.2f}. Mean "
        f"pairwise correlation {c4['mean_pairwise_correlation']:.3f}. "
        f"Point-in-time price correlations average "
        f"{claims['risk_model']['mean_pairwise_correlation_of_prices']:.3f} "
        f"with mean effective breadth "
        f"{claims['risk_model']['mean_effective_breadth_of_prices']:.2f} across "
        f"{claims['risk_model']['mean_markets_in_risk_model']:.0f} markets.\n")

    add("\n## C5 trend horizons\n")
    add(md_table(t5))

    add("\n## C10 untargeted risk dispersion\n")
    c10 = claims["C10"]
    q = pd.DataFrame({
        "quantile": list(c10["risk_to_target_quantiles"].keys()),
        "untargeted_risk_to_target": list(
            c10["risk_to_target_quantiles"].values()),
    })
    add(md_table(q))
    add(f"\nThe fixed-multiplier book's post-buffer ex-ante risk spans "
        f"{c10['risk_to_target_min']:.2f}x to "
        f"{c10['risk_to_target_max']:.2f}x target; "
        f"{c10['share_outside_claimed_range']:.1%} of days fall outside the "
        "source's 0.3x-3.0x range.\n")

    (RESULTS_DIR / "report.md").write_text("\n".join(parts) + "\n")
    print(f"wrote {RESULTS_DIR / 'report.md'}")


if __name__ == "__main__":
    main()
